# Generated by Django 5.2.6 on 2025-09-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
